#!/usr/bin/env python3
"""
Test Files Cleanup Script

This script cleans up test files and directories generated by test_and_validation.py
"""

import os
import shutil
import argparse
from pathlib import Path
import glob

def cleanup_test_files(project_dir: str, confirm: bool = True):
    """Clean up test files and directories"""
    project_path = Path(project_dir)
    
    # Define paths to clean
    paths_to_clean = [
        project_path / "result" / "test_results",
        project_path / "audio" / "test_audio", 
        project_path / "configs" / "test_configs"
    ]
    
    # Find files to clean
    files_to_clean = []
    dirs_to_clean = []
    
    for path in paths_to_clean:
        if path.exists():
            if path.is_dir():
                dirs_to_clean.append(path)
                # Count files in directory
                file_count = len(list(path.rglob('*'))) if path.exists() else 0
                files_to_clean.extend(list(path.rglob('*')))
            else:
                files_to_clean.append(path)
    
    # Also clean any test CSV files in result directory
    result_dir = project_path / "result"
    if result_dir.exists():
        test_csvs = list(result_dir.glob("test_*.csv"))
        files_to_clean.extend(test_csvs)
    
    print("TEST FILES CLEANUP")
    print("="*50)
    print(f"Project directory: {project_path}")
    print(f"Directories to remove: {len(dirs_to_clean)}")
    print(f"Files to remove: {len([f for f in files_to_clean if f.is_file()])}")
    
    if dirs_to_clean:
        print(f"\nDirectories:")
        for dir_path in dirs_to_clean:
            file_count = len([f for f in dir_path.rglob('*') if f.is_file()]) if dir_path.exists() else 0
            print(f"  • {dir_path} ({file_count} files)")
    
    test_csvs = [f for f in files_to_clean if f.name.startswith('test_') and f.name.endswith('.csv')]
    if test_csvs:
        print(f"\nTest CSV files:")
        for csv_file in test_csvs[:5]:  # Show first 5
            print(f"  • {csv_file.name}")
        if len(test_csvs) > 5:
            print(f"  ... and {len(test_csvs) - 5} more")
    
    if not dirs_to_clean and not files_to_clean:
        print("\nNo test files found to clean.")
        return
    
    if confirm:
        print(f"\nThis will permanently delete all test files and directories.")
        response = input("Do you want to proceed? (y/N): ").lower()
        if response != 'y' and response != 'yes':
            print("Cleanup cancelled.")
            return
    
    # Perform cleanup
    removed_dirs = 0
    removed_files = 0
    errors = []
    
    print(f"\nCleaning up...")
    
    # Remove directories
    for dir_path in dirs_to_clean:
        try:
            if dir_path.exists():
                shutil.rmtree(dir_path)
                removed_dirs += 1
                print(f"Removed directory: {dir_path.name}")
        except Exception as e:
            errors.append(f"Could not remove directory {dir_path}: {e}")
    
    # Remove individual test CSV files
    for csv_file in test_csvs:
        try:
            if csv_file.exists():
                csv_file.unlink()
                removed_files += 1
                print(f"Removed file: {csv_file.name}")
        except Exception as e:
            errors.append(f"Could not remove file {csv_file}: {e}")
    
    # Summary
    print(f"\nCleanup completed!")
    print(f"Removed {removed_dirs} directories")
    print(f"Removed {removed_files} files")
    
    if errors:
        print(f"\nErrors encountered:")
        for error in errors:
            print(f"  • {error}")
    else:
        print("All test files cleaned successfully!")

def main():
    parser = argparse.ArgumentParser(description="Clean up test files generated by test_and_validation.py")
    
    parser.add_argument("--project_dir", type=str,
                       default="/home/jieshiang/Desktop/GitHub/Codec_comparison",
                       help="Project root directory path")
    parser.add_argument("--yes", action="store_true",
                       help="Skip confirmation prompt")
    parser.add_argument("--dry_run", action="store_true", 
                       help="Show what would be deleted without actually deleting")
    
    args = parser.parse_args()
    
    if args.dry_run:
        print("DRY RUN MODE - No files will be deleted")
        cleanup_test_files(args.project_dir, confirm=False)
        print("\nDry run completed. Use without --dry_run to actually delete files.")
    else:
        cleanup_test_files(args.project_dir, confirm=not args.yes)

if __name__ == "__main__":
    main()